import{useMemo,useState}from'react';
const actions=['Reports and Status','Model vs. MTO vs. PID Check','Equipment Status','ISO Planning and Management','Support Planning and Management'];
const modules=['M0C','M1C','M2C','M3C','M4C','M5C','M1P','M2P','M3P','M4P','M5P','M1S','M2S','M3S','M4S','M5S'];
const e3d=['MTO Report','Valve Report','Pipe Branch Report','Primary Support Report','ATTA Report','Elbow and Bend Report','Equipment Orientation and Position Report','Special Item Report','Nozzle Report'];
const records=Object.fromEntries(modules.map(m=>[m,Object.fromEntries(e3d.map(r=>[r,[]]))]));
const count=(m,r)=>records[m]?.[r]?.length??0;
const groups=[{title:'E3D Reports',items:e3d},{title:'Modelling Status',items:['2 Inch and Below','3 Inch and 4 Inch','6 Inch and Above','Fluid Code','Material and Specification']},{title:'Gate Status',items:['Line Status','Equipment Status','Escape Route Status','Safety Equipment Status','Material Handling Status','Support Status']},{title:'ISO Utility',items:['Data Consistency','Gusset Report','ISO Break Check','Specification Mismatch','Pipe Aid Check','Pipe Insulation Check','Vendor Document Check','Weld Gap Check','Support Tag Check','Clash Report']}];
export default function App(){const[page,setPage]=useState('home'),[title,setTitle]=useState(''),[back,setBack]=useState('home');const go=p=>{setPage(p);scrollTo(0,0)},blank=(t,b='home')=>{setTitle(t);setBack(b);go('blank')};if(page==='reports')return <Reports back={()=>go('home')} open={t=>blank(t,'reports')}/>;if(page==='blank')return <Layout title={title} sub="Content Placeholder" back={()=>go(back)}><div className="blank"><b>RGT</b><small>CONTENT PLACEHOLDER</small><h2>{title}</h2><p>No project data or report has been added to this page yet.</p><button onClick={()=>go(back)}>Return to Previous Page</button></div></Layout>;return <Home reports={()=>go('reports')} blank={blank}/>}
function Home({reports,blank}){const act=(code,name,a)=>code==='4193'&&a==='Reports and Status'?reports():blank(`${code} · ${name} · ${a}`);return <><section className="hero"><div/><main><p>FPSO PROJECT PORTAL</p><h1>Reports Generate Tools</h1></main></section><section className="dash"><div className="projects"><Card code="4193" name="HAMMER HEAD" action={a=>act('4193','HAMMER HEAD',a)}/><Card code="4173" name="Gato do Mato" action={a=>act('4173','Gato do Mato',a)}/></div></section></>}
function Card({code,name,action}){return <article className="card"><header><b>{code}</b><div><p>PROJECT DASHBOARD</p><h2>{name}</h2></div></header><section>{actions.map(a=><button key={a} onClick={()=>action(a)}>{a}</button>)}</section></article>}
function Reports({back,open}){const[q,setQ]=useState(''),[selected,setSelected]=useState(null);const list=useMemo(()=>modules.filter(m=>m.toLowerCase().includes(q.trim().toLowerCase())),[q]);return <Layout title="Reports and Status" sub="Project 4193 · HAMMER HEAD" back={back}><div className="workspace"><aside className="modules"><header><p>PROJECT MODULES</p><h2>Module List</h2></header><label>⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search module name"/></label><section>{list.map(m=><button className={selected===m?'active':''} key={m} onClick={()=>setSelected(selected===m?null:m)}>{m}</button>)}</section></aside><article className="reports">{selected?<><header><div><p>SELECTED MODULE</p><h2>{selected}</h2><span>Report counts are calculated from real records in this module.</span></div><button onClick={()=>setSelected(null)}>Close</button></header><section>{e3d.map(r=><button key={r} onClick={()=>open(`${selected} · ${r}`)}><span>{r}</span><b>{count(selected,r)}</b></button>)}</section></>:<div className="empty"><b>RGT</b><p>MODULE SELECTION</p><h2>Select a module</h2><span>Module names remain fixed on the left. Select a module to open its reports on the right.</span></div>}</article></div><Integrated open={open}/></Layout>}
function Integrated({open}){return <section className="integrated"><header><p>INTEGRATED TOOL</p><h2>Overall Project and Module-Wise Status</h2></header><div>{groups.map((g,i)=><article key={g.title}><h3>{g.title}</h3><section>{g.items.map((x,j)=><button className={`c${(i+j)%5}`} key={x} onClick={()=>open(x)}>{x}</button>)}</section></article>)}</div></section>}
function Layout({title,sub,back,children}){return <main className="page"><header className="top"><button onClick={back}>Back</button><div><p>REPORTS GENERATE TOOLS</p><h1>{title}</h1><span>{sub}</span></div></header><section className="content">{children}</section></main>}
