-- Report Generate Tool - central module list
-- Run this once in Supabase SQL Editor.

create table if not exists public.modules (
  id bigint generated by default as identity primary key,
  module_name text not null unique,
  sort_order integer not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists modules_sort_order_idx
on public.modules(sort_order);

alter table public.modules enable row level security;

drop policy if exists "Anyone can read active modules" on public.modules;

create policy "Anyone can read active modules"
on public.modules
for select
to anon, authenticated
using (active = true);

-- The website server calls this RPC with the Supabase service-role key.
-- It replaces the central module list atomically and preserves the Excel order.
create or replace function public.replace_modules(p_modules text[])
returns setof public.modules
language plpgsql
security definer
set search_path = public
as $$
declare
  item text;
  idx integer := 0;
  cleaned text;
begin
  delete from public.modules;

  foreach item in array coalesce(p_modules, array[]::text[]) loop
    cleaned := btrim(item);
    if cleaned is null or cleaned = '' then
      continue;
    end if;

    idx := idx + 1;

    insert into public.modules(module_name, sort_order, active, updated_at)
    values (cleaned, idx, true, now())
    on conflict (module_name)
    do update set sort_order = excluded.sort_order,
                  active = true,
                  updated_at = now();
  end loop;

  return query
  select *
  from public.modules
  where active = true
  order by sort_order asc;
end;
$$;

revoke all on function public.replace_modules(text[]) from public, anon, authenticated;
grant execute on function public.replace_modules(text[]) to service_role;
