import{useMemo,useState}from'react';import*as XLSX from'xlsx';
const ACTIONS=['Reports and Status','Model vs. MTO vs. PID Check','Equipment Status','ISO Planning and Management','Support Planning and Management'];
const MODULES=['M0C','M1C','M2C','M3C','M4C','M5C','M1P','M2P','M3P','M4P','M5P','M1S','M2S','M3S','M4S','M5S'];
const E3D=['MTO Report','Valve Report','Pipe Branch Report','Primary Support Report','ATTA Report','Elbow and Bend Report','Equipment Orientation and Position Report','Special Item Report','Nozzle Report'];
const GROUPS=[['E3D Reports',E3D],['Modelling Status',['2 Inch and Below','3 Inch and 4 Inch','6 Inch and Above','Fluid Code','Material and Specification']],['Gate Status',['Line Status','Equipment Status','Escape Route Status','Safety Equipment Status','Material Handling Status','Support Status']],['ISO Utility',['Data Consistency','Gusset Report','ISO Break Check','Specification Mismatch','Pipe Aid Check','Pipe Insulation Check','Vendor Document Check','Weld Gap Check','Support Tag Check','Clash Report']]];
const normalize=v=>String(v??'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]/g,'');
const isOverallHeader=v=>{const n=normalize(v);return n==='overall'||n.startsWith('overallcount')||n.startsWith('overallvalue')||(n.includes('overall')&&(n.includes('count')||n.includes('value')))};
const numberFrom=v=>{if(typeof v==='number')return Number.isFinite(v)?v:null;if(typeof v!=='string'||!v.trim())return null;let t=v.trim(),neg=false;if(/^\(.*\)$/.test(t)){neg=true;t=t.slice(1,-1)}t=t.replace(/,/g,'').replace(/[^0-9.+-]/g,'');if(!t||!/[0-9]/.test(t))return null;const n=Number(t);return Number.isFinite(n)?(neg?-Math.abs(n):n):null};
const sumOverall=buffer=>{const wb=XLSX.read(buffer,{type:'array',cellDates:false});let total=0;for(const name of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,raw:true,defval:null});const limit=Math.min(rows.length,25);for(let r=0;r<limit;r++){const cols=[];(rows[r]??[]).forEach((v,c)=>{if(isOverallHeader(v))cols.push(c)});if(!cols.length)continue;for(let i=r+1;i<rows.length;i++)for(const c of cols){const n=numberFrom(rows[i]?.[c]);if(n!==null)total+=n}break}}return total};
async function scanDirectory(handle,prefix=''){const files=[];for await(const entry of handle.values()){const relative=prefix?`${prefix}/${entry.name}`:entry.name;if(entry.kind==='directory')files.push(...await scanDirectory(entry,relative));else if(/\.(xlsx|xls|xlsm|xlsb)$/i.test(entry.name))files.push({handle:entry,path:relative,name:entry.name})}return files}
function scoreFile(file,moduleName,reportName){const n=normalize(file.path),m=normalize(moduleName),r=normalize(reportName);if(!n.includes(m))return-1;const tokens=reportName.toLowerCase().split(/[^a-z0-9]+/).filter(t=>t.length>1&&t!=='report'),hits=tokens.filter(t=>n.includes(normalize(t))).length;if(!n.includes(r)&&hits<Math.max(1,tokens.length-1))return-1;return(n.includes(r)?100:0)+hits*10+(normalize(file.name).startsWith(m)?20:0)}
function findFile(files,moduleName,reportName){return files.map(file=>({file,score:scoreFile(file,moduleName,reportName)})).filter(x=>x.score>=0).sort((a,b)=>b.score-a.score||a.file.path.localeCompare(b.file.path))[0]?.file??null}
export default function App(){const[page,setPage]=useState('home'),[title,setTitle]=useState(''),[from,setFrom]=useState('home');const go=p=>{setPage(p);scrollTo(0,0)},blank=(t,f)=>{setTitle(t);setFrom(f);go('blank')};if(page==='reports')return<Reports back={()=>go('home')} open={t=>blank(t,'reports')}/>;if(page==='blank')return<Layout title={title} sub="Content Placeholder" back={()=>go(from)}><div className="blank"><b>RGT</b><p>CONTENT PLACEHOLDER</p><h2>{title}</h2><span>No project data or report has been added to this page yet.</span><button onClick={()=>go(from)}>Return to Previous Page</button></div></Layout>;return<Home reports={()=>go('reports')} blank={t=>blank(t,'home')}/>}
function Home({reports,blank}){const action=(code,name,a)=>code==='4193'&&a==='Reports and Status'?reports():blank(`${code} · ${name} · ${a}`);return<><section className="hero"><div/><main><p>FPSO PROJECT PORTAL</p><h1>Reports Generate Tools</h1></main></section><section className="dashboard"><div className="projects"><Card code="4193" name="HAMMER HEAD" click={a=>action('4193','HAMMER HEAD',a)}/><Card code="4173" name="Gato do Mato" click={a=>action('4173','Gato do Mato',a)}/></div></section></>}
function Card({code,name,click}){return<article className="card"><header><b>{code}</b><div><p>PROJECT DASHBOARD</p><h2>{name}</h2></div></header><section>{ACTIONS.map(a=><button key={a} onClick={()=>click(a)}>{a}</button>)}</section></article>}
function Reports({back,open}){const[q,setQ]=useState(''),[selected,setSelected]=useState(null),[folderName,setFolderName]=useState(''),[files,setFiles]=useState([]),[counts,setCounts]=useState({}),[busy,setBusy]=useState(false);const list=useMemo(()=>MODULES.filter(m=>m.toLowerCase().includes(q.trim().toLowerCase())),[q]);
const calculateCounts=async(moduleName,currentFiles=files)=>{if(!moduleName||!currentFiles.length){setCounts({});return}setBusy(true);const next={};for(const report of E3D){const match=findFile(currentFiles,moduleName,report);if(!match){next[report]=0;continue}try{const file=await match.handle.getFile();next[report]=sumOverall(await file.arrayBuffer())}catch{next[report]=0}}setCounts(next);setBusy(false)};
const connectFolder=async()=>{if(!('showDirectoryPicker'in window)){alert('This browser does not support folder connection. Use Microsoft Edge or Google Chrome.');return}try{const handle=await window.showDirectoryPicker({mode:'read'});const scanned=await scanDirectory(handle);setFolderName(handle.name);setFiles(scanned);await calculateCounts(selected,scanned)}catch(error){if(error.name!=='AbortError')alert('Folder connection failed.')}};
const chooseModule=async moduleName=>{const next=selected===moduleName?null:moduleName;setSelected(next);await calculateCounts(next)};
const download=async report=>{if(!selected)return;const match=findFile(files,selected,report);if(!match){alert('No matching Excel report found. Connect the correct folder or check the file name.');return}const file=await match.handle.getFile();const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)};
return<Layout title="Reports and Status" sub="Project 4193 · HAMMER HEAD" back={back}><div className="work"><aside><header><p>PROJECT MODULES</p><h2>Module List</h2></header><div className="folder-connect"><button onClick={connectFolder}>Connect Excel Folder</button><span>{folderName?`Connected: ${folderName}`:'No folder connected'}</span></div><label>⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search module name"/></label><section>{list.map(m=><button className={m===selected?'sel':''} key={m} onClick={()=>chooseModule(m)}>{m}</button>)}</section></aside><article className="reports">{selected?<><header><div><p>SELECTED MODULE</p><h2>{selected}</h2></div><button onClick={()=>setSelected(null)}>Close</button></header><section>{E3D.map(r=><button key={r} onClick={()=>download(r)}><span>{r}</span><b>{busy?'…':counts[r]??0}</b></button>)}</section></>:<div className="empty"><b>RGT</b><p>MODULE SELECTION</p><h2>Select a module</h2><span>Select a module on the left to open reports here.</span></div>}</article></div><Integrated open={open}/></Layout>}
function Integrated({open}){return<section className="integrated"><header><p>INTEGRATED TOOL</p><h2>Overall Project and Module-Wise Status</h2></header><div>{GROUPS.map(([g,items],gi)=><article key={g}><h3>{g}</h3><section>{items.map((x,i)=><button className={`c${(gi+i)%5}`} key={x} onClick={()=>open(x)}>{x}</button>)}</section></article>)}</div></section>}
function Layout({title,sub,back,children}){return<main className="page"><header className="top"><button onClick={back}>Back</button><div><p>REPORTS GENERATE TOOLS</p><h1>{title}</h1><span>{sub}</span></div></header><section className="content">{children}</section></main>}
