import{useMemo,useState}from'react';
const ACTIONS=['Reports and Status','Model vs. MTO vs. PID Check','Equipment Status','ISO Planning and Management','Support Planning and Management'];
const MODULES=['M0C','M1C','M2C','M3C','M4C','M5C','M1P','M2P','M3P','M4P','M5P','M1S','M2S','M3S','M4S','M5S'];
const E3D=['MTO Report','Valve Report','Pipe Branch Report','Primary Support Report','ATTA Report','Elbow and Bend Report','Equipment Orientation and Position Report','Special Item Report','Nozzle Report'];
const RECORDS=Object.fromEntries(MODULES.map(m=>[m,Object.fromEntries(E3D.map(r=>[r,[]]))]));
const count=(m,r)=>RECORDS[m]?.[r]?.length??0;
const GROUPS=[['E3D Reports',E3D],['Modelling Status',['2 Inch and Below','3 Inch and 4 Inch','6 Inch and Above','Fluid Code','Material and Specification']],['Gate Status',['Line Status','Equipment Status','Escape Route Status','Safety Equipment Status','Material Handling Status','Support Status']],['ISO Utility',['Data Consistency','Gusset Report','ISO Break Check','Specification Mismatch','Pipe Aid Check','Pipe Insulation Check','Vendor Document Check','Weld Gap Check','Support Tag Check','Clash Report']]];
export default function App(){const[page,setPage]=useState('home'),[title,setTitle]=useState(''),[from,setFrom]=useState('home');const go=p=>{setPage(p);scrollTo(0,0)},blank=(t,f)=>{setTitle(t);setFrom(f);go('blank')};if(page==='reports')return <Reports back={()=>go('home')} open={t=>blank(t,'reports')}/>;if(page==='blank')return <Layout title={title} sub="Content Placeholder" back={()=>go(from)}><div className="blank"><b>RGT</b><p>CONTENT PLACEHOLDER</p><h2>{title}</h2><span>No project data or report has been added to this page yet.</span><button onClick={()=>go(from)}>Return to Previous Page</button></div></Layout>;return <Home reports={()=>go('reports')} blank={t=>blank(t,'home')}/>}
function Home({reports,blank}){const action=(code,name,a)=>code==='4193'&&a==='Reports and Status'?reports():blank(`${code} · ${name} · ${a}`);return <><section className="hero"><div/><main><p>FPSO PROJECT PORTAL</p><h1>Reports Generate Tools</h1></main></section><section className="dashboard"><div className="projects"><Card code="4193" name="HAMMER HEAD" click={a=>action('4193','HAMMER HEAD',a)}/><Card code="4173" name="Gato do Mato" click={a=>action('4173','Gato do Mato',a)}/></div></section></>}
function Card({code,name,click}){return <article className="card"><header><b>{code}</b><div><p>PROJECT DASHBOARD</p><h2>{name}</h2></div></header><section>{ACTIONS.map(a=><button key={a} onClick={()=>click(a)}>{a}</button>)}</section></article>}
function Reports({back,open}){const[q,setQ]=useState(''),[selected,setSelected]=useState(null);const list=useMemo(()=>MODULES.filter(m=>m.toLowerCase().includes(q.toLowerCase().trim())),[q]);return <Layout title="Reports and Status" sub="Project 4193 · HAMMER HEAD" back={back}><div className="work"><aside><header><p>PROJECT MODULES</p><h2>Module List</h2></header><label>⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search module name"/></label><section>{list.map(m=><button className={m===selected?'sel':''} key={m} onClick={()=>setSelected(s=>s===m?null:m)}>{m}</button>)}</section></aside><article className="reports">{selected?<><header><div><p>SELECTED MODULE</p><h2>{selected}</h2></div><button onClick={()=>setSelected(null)}>Close</button></header><section>{E3D.map(r=><button key={r} onClick={()=>open(`${selected} · ${r}`)}><span>{r}</span><b>{count(selected,r)}</b></button>)}</section></>:<div className="empty"><b>RGT</b><p>MODULE SELECTION</p><h2>Select a module</h2><span>Select a module on the left to open reports here.</span></div>}</article></div><section className="integrated"><header><p>INTEGRATED TOOL</p><h2>Overall Project and Module-Wise Status</h2></header><div>{GROUPS.map(([g,items],gi)=><article key={g}><h3>{g}</h3><section>{items.map((x,i)=><button className={`c${(gi+i)%5}`} key={x} onClick={()=>open(x)}>{x}</button>)}</section></article>)}</div></section></Layout>}
function Layout({title,sub,back,children}){return <main className="page"><header className="top"><button onClick={back}>Back</button><div><p>REPORTS GENERATE TOOLS</p><h1>{title}</h1><span>{sub}</span></div></header><section className="content">{children}</section></main>}
